# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'serverGUI.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Server(object):
    def setupUi(self, Server):
        Server.setObjectName("Server")
        Server.resize(564, 265)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/sfondo/2_icon38Server.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Server.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(Server)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.statoServerLabel = QtWidgets.QLabel(self.centralwidget)
        self.statoServerLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.statoServerLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.statoServerLabel.setObjectName("statoServerLabel")
        self.horizontalLayout.addWidget(self.statoServerLabel)
        self.statoLabel = QtWidgets.QLabel(self.centralwidget)
        self.statoLabel.setObjectName("statoLabel")
        self.horizontalLayout.addWidget(self.statoLabel)
        self.imgLabel = QtWidgets.QLabel(self.centralwidget)
        self.imgLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.imgLabel.setObjectName("imgLabel")
        self.horizontalLayout.addWidget(self.imgLabel)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollContent = QtWidgets.QWidget()
        self.scrollContent.setGeometry(QtCore.QRect(0, 0, 529, 472))
        self.scrollContent.setObjectName("scrollContent")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollContent)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label7 = QtWidgets.QLabel(self.scrollContent)
        self.label7.setObjectName("label7")
        self.gridLayout_2.addWidget(self.label7, 7, 0, 1, 1)
        self.label15 = QtWidgets.QLabel(self.scrollContent)
        self.label15.setObjectName("label15")
        self.gridLayout_2.addWidget(self.label15, 15, 0, 1, 1)
        self.label19 = QtWidgets.QLabel(self.scrollContent)
        self.label19.setObjectName("label19")
        self.gridLayout_2.addWidget(self.label19, 20, 0, 1, 1)
        self.label16 = QtWidgets.QLabel(self.scrollContent)
        self.label16.setObjectName("label16")
        self.gridLayout_2.addWidget(self.label16, 16, 0, 1, 1)
        self.label17 = QtWidgets.QLabel(self.scrollContent)
        self.label17.setObjectName("label17")
        self.gridLayout_2.addWidget(self.label17, 17, 0, 1, 1)
        self.label18 = QtWidgets.QLabel(self.scrollContent)
        self.label18.setObjectName("label18")
        self.gridLayout_2.addWidget(self.label18, 18, 0, 1, 1)
        self.label12 = QtWidgets.QLabel(self.scrollContent)
        self.label12.setObjectName("label12")
        self.gridLayout_2.addWidget(self.label12, 12, 0, 1, 1)
        self.label1 = QtWidgets.QLabel(self.scrollContent)
        self.label1.setObjectName("label1")
        self.gridLayout_2.addWidget(self.label1, 1, 0, 1, 1)
        self.label2 = QtWidgets.QLabel(self.scrollContent)
        self.label2.setObjectName("label2")
        self.gridLayout_2.addWidget(self.label2, 2, 0, 1, 1)
        self.label3 = QtWidgets.QLabel(self.scrollContent)
        self.label3.setObjectName("label3")
        self.gridLayout_2.addWidget(self.label3, 3, 0, 1, 1)
        self.label0 = QtWidgets.QLabel(self.scrollContent)
        self.label0.setObjectName("label0")
        self.gridLayout_2.addWidget(self.label0, 0, 0, 1, 1)
        self.label6 = QtWidgets.QLabel(self.scrollContent)
        self.label6.setObjectName("label6")
        self.gridLayout_2.addWidget(self.label6, 6, 0, 1, 1)
        self.label5 = QtWidgets.QLabel(self.scrollContent)
        self.label5.setObjectName("label5")
        self.gridLayout_2.addWidget(self.label5, 5, 0, 1, 1)
        self.label9 = QtWidgets.QLabel(self.scrollContent)
        self.label9.setObjectName("label9")
        self.gridLayout_2.addWidget(self.label9, 9, 0, 1, 1)
        self.label11 = QtWidgets.QLabel(self.scrollContent)
        self.label11.setObjectName("label11")
        self.gridLayout_2.addWidget(self.label11, 11, 0, 1, 1)
        self.label10 = QtWidgets.QLabel(self.scrollContent)
        self.label10.setObjectName("label10")
        self.gridLayout_2.addWidget(self.label10, 10, 0, 1, 1)
        self.label13 = QtWidgets.QLabel(self.scrollContent)
        self.label13.setObjectName("label13")
        self.gridLayout_2.addWidget(self.label13, 13, 0, 1, 1)
        self.label8 = QtWidgets.QLabel(self.scrollContent)
        self.label8.setObjectName("label8")
        self.gridLayout_2.addWidget(self.label8, 8, 0, 1, 1)
        self.label4 = QtWidgets.QLabel(self.scrollContent)
        self.label4.setObjectName("label4")
        self.gridLayout_2.addWidget(self.label4, 4, 0, 1, 1)
        self.label14 = QtWidgets.QLabel(self.scrollContent)
        self.label14.setObjectName("label14")
        self.gridLayout_2.addWidget(self.label14, 14, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollContent)
        self.verticalLayout.addWidget(self.scrollArea)
        self.gridLayout.addLayout(self.verticalLayout, 0, 1, 1, 1)
        Server.setCentralWidget(self.centralwidget)

        self.retranslateUi(Server)
        QtCore.QMetaObject.connectSlotsByName(Server)

    def retranslateUi(self, Server):
        _translate = QtCore.QCoreApplication.translate
        Server.setWindowTitle(_translate("Server", "MainWindow"))
        self.statoServerLabel.setText(_translate("Server", "Stato server:"))
        self.statoLabel.setText(_translate("Server", "***"))
        self.imgLabel.setText(_translate("Server", "<html><head/><body><p><img src=\":/sfondo/gray.png\"/></p></body></html>"))
        self.label7.setText(_translate("Server", "7"))
        self.label15.setText(_translate("Server", "15"))
        self.label19.setText(_translate("Server", "19"))
        self.label16.setText(_translate("Server", "16"))
        self.label17.setText(_translate("Server", "17"))
        self.label18.setText(_translate("Server", "18"))
        self.label12.setText(_translate("Server", "12"))
        self.label1.setText(_translate("Server", "1"))
        self.label2.setText(_translate("Server", "2"))
        self.label3.setText(_translate("Server", "3"))
        self.label0.setText(_translate("Server", "0"))
        self.label6.setText(_translate("Server", "6"))
        self.label5.setText(_translate("Server", "5"))
        self.label9.setText(_translate("Server", "9"))
        self.label11.setText(_translate("Server", "11"))
        self.label10.setText(_translate("Server", "10"))
        self.label13.setText(_translate("Server", "13"))
        self.label8.setText(_translate("Server", "8"))
        self.label4.setText(_translate("Server", "4"))
        self.label14.setText(_translate("Server", "14"))

import sfondoCantina_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Server = QtWidgets.QMainWindow()
    ui = Ui_Server()
    ui.setupUi(Server)
    Server.show()
    sys.exit(app.exec_())

