from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 540)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.passwordLabel = QtWidgets.QLabel(self.centralwidget)
        self.passwordLabel.setObjectName("passwordLabel")
        self.gridLayout.addWidget(self.passwordLabel, 3, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 0, 2, 1, 1)
        self.passwordLine = QtWidgets.QLineEdit(self.centralwidget)
        self.passwordLine.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordLine.setObjectName("passwordLine")
        self.gridLayout.addWidget(self.passwordLine, 3, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 1, 3, 1, 1)
        self.usernameLabel = QtWidgets.QLabel(self.centralwidget)
        self.usernameLabel.setObjectName("usernameLabel")
        self.gridLayout.addWidget(self.usernameLabel, 1, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 5, 1, 1, 1)
        self.fallimentoLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.fallimentoLabel.setFont(font)
        self.fallimentoLabel.setText("")
        self.fallimentoLabel.setObjectName("fallimentoLabel")
        self.gridLayout.addWidget(self.fallimentoLabel, 4, 1, 1, 2)
        self.inviaButton = QtWidgets.QPushButton(self.centralwidget)
        self.inviaButton.setObjectName("inviaButton")
        self.inviaButton.clicked.connect(lambda: self.invia_click(self.fallimentoLabel))
        self.gridLayout.addWidget(self.inviaButton, 6, 1, 1, 2)
        self.usernameLine = QtWidgets.QLineEdit(self.centralwidget)
        self.usernameLine.setObjectName("usernameLine")
        self.gridLayout.addWidget(self.usernameLine, 1, 2, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 3, 3, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 3, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem6, 7, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "LOGIN"))
        self.passwordLabel.setText(_translate("MainWindow", "password:"))
        self.usernameLabel.setText(_translate("MainWindow", "username:"))
        self.inviaButton.setText(_translate("MainWindow", "INVIA"))

    def invia_click(self,fallimento):
        import socket
        client=socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        client.connect(("localhost",8080))
        userText=self.usernameLine.text()
        passwdText=self.passwordLine.text()
        cred=userText+","+passwdText
        client.send(cred.encode())
        risp=client.recv(1024).decode()
        if risp=="credenziali_errate":
            self.fallimentoLabel.setText("credenziali errate")
            client.close()
        elif risp=="errore_connessione":
            self.fallimentoLabel.setText("errore_connessione")
            client.close()
        elif risp=="accesso_corretto":
            self.fallimentoLabel.setText("accesso corretto")
            client.close()
            self.refresh(MainWindow)

#prototipo refresh inizio

    def refresh(self, MainWindow):
        ui=Ui_Cantina()
        ui.functCantina(MainWindow)

class Ui_Cantina(object):
    def functCantina(self, Cantina):
        Cantina.setObjectName("Cantina")
        Cantina.setWindowModality(QtCore.Qt.WindowModal)
        Cantina.setEnabled(True)
        Cantina.resize(637, 769)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        Cantina.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("2_grappoloicon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Cantina.setWindowIcon(icon)
        Cantina.setAutoFillBackground(True)
        Cantina.setStyleSheet("")
        Cantina.setAnimated(True)
        Cantina.setUnifiedTitleAndToolBarOnMac(True)
        self.centralwidget = QtWidgets.QWidget(Cantina)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.mappacantina = QtWidgets.QLabel(self.centralwidget)
        self.mappacantina.setObjectName("mappacantina")
        self.gridLayout_2.addWidget(self.mappacantina, 1, 0, 1, 1)
        self.dataora = QtWidgets.QDateTimeEdit(self.centralwidget)
        self.dataora.setMinimumSize(QtCore.QSize(496, 0))
        self.dataora.setFocusPolicy(QtCore.Qt.NoFocus)
        self.dataora.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.dataora.setWrapping(False)
        self.dataora.setFrame(False)
        self.dataora.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dataora.setReadOnly(True)
        self.dataora.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.dataora.setAccelerated(False)
        self.dataora.setObjectName("dataora")
        self.gridLayout_2.addWidget(self.dataora, 0, 0, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setStyleSheet("background-color: rgb(233, 236, 255);")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.lista = QtWidgets.QWidget()
        self.lista.setGeometry(QtCore.QRect(0, 0, 102, 1101))
        self.lista.setObjectName("lista")
        self.gridLayout = QtWidgets.QGridLayout(self.lista)
        self.gridLayout.setObjectName("gridLayout")
        self.vv16 = QtWidgets.QPushButton(self.lista)
        self.vv16.setObjectName("vv16")
        self.gridLayout.addWidget(self.vv16, 3, 0, 1, 1)
        self.locale2 = QtWidgets.QPushButton(self.lista)
        font = QtGui.QFont()
        font.setUnderline(True)
        self.locale2.setFont(font)
        self.locale2.setStyleSheet("background-color: rgb(221, 237, 255);")
        self.locale2.setObjectName("locale2")
        self.gridLayout.addWidget(self.locale2, 9, 0, 1, 1)
        self.vv14 = QtWidgets.QPushButton(self.lista)
        self.vv14.setObjectName("vv14")
        self.gridLayout.addWidget(self.vv14, 1, 0, 1, 1)
        self.vv22 = QtWidgets.QPushButton(self.lista)
        self.vv22.setObjectName("vv22")
        self.gridLayout.addWidget(self.vv22, 21, 0, 1, 1)
        self.vv33 = QtWidgets.QPushButton(self.lista)
        self.vv33.setObjectName("vv33")
        self.gridLayout.addWidget(self.vv33, 32, 0, 1, 1)
        self.vv7 = QtWidgets.QPushButton(self.lista)
        self.vv7.setObjectName("vv7")
        self.gridLayout.addWidget(self.vv7, 13, 0, 1, 1)
        self.vv32 = QtWidgets.QPushButton(self.lista)
        self.vv32.setObjectName("vv32")
        self.gridLayout.addWidget(self.vv32, 31, 0, 1, 1)
        self.vv19 = QtWidgets.QPushButton(self.lista)
        self.vv19.setObjectName("vv19")
        self.gridLayout.addWidget(self.vv19, 6, 0, 1, 1)
        self.vv15 = QtWidgets.QPushButton(self.lista)
        self.vv15.setObjectName("vv15")
        self.gridLayout.addWidget(self.vv15, 2, 0, 1, 1)
        self.vv27 = QtWidgets.QPushButton(self.lista)
        self.vv27.setObjectName("vv27")
        self.gridLayout.addWidget(self.vv27, 26, 0, 1, 1)
        self.vv25 = QtWidgets.QPushButton(self.lista)
        self.vv25.setObjectName("vv25")
        self.gridLayout.addWidget(self.vv25, 24, 0, 1, 1)
        self.vv23 = QtWidgets.QPushButton(self.lista)
        self.vv23.setObjectName("vv23")
        self.gridLayout.addWidget(self.vv23, 22, 0, 1, 1)
        self.vv8 = QtWidgets.QPushButton(self.lista)
        self.vv8.setObjectName("vv8")
        self.gridLayout.addWidget(self.vv8, 14, 0, 1, 1)
        self.vv29 = QtWidgets.QPushButton(self.lista)
        self.vv29.setObjectName("vv29")
        self.gridLayout.addWidget(self.vv29, 28, 0, 1, 1)
        self.vv30 = QtWidgets.QPushButton(self.lista)
        self.vv30.setObjectName("vv30")
        self.gridLayout.addWidget(self.vv30, 29, 0, 1, 1)
        self.vv17 = QtWidgets.QPushButton(self.lista)
        self.vv17.setObjectName("vv17")
        self.gridLayout.addWidget(self.vv17, 4, 0, 1, 1)
        self.locale3 = QtWidgets.QPushButton(self.lista)
        font = QtGui.QFont()
        font.setUnderline(True)
        self.locale3.setFont(font)
        self.locale3.setStyleSheet("background-color: rgb(221, 237, 255);")
        self.locale3.setObjectName("locale3")
        self.gridLayout.addWidget(self.locale3, 20, 0, 1, 1)
        self.vv28 = QtWidgets.QPushButton(self.lista)
        self.vv28.setObjectName("vv28")
        self.gridLayout.addWidget(self.vv28, 27, 0, 1, 1)
        self.vv24 = QtWidgets.QPushButton(self.lista)
        self.vv24.setObjectName("vv24")
        self.gridLayout.addWidget(self.vv24, 23, 0, 1, 1)
        self.vv20 = QtWidgets.QPushButton(self.lista)
        self.vv20.setObjectName("vv20")
        self.gridLayout.addWidget(self.vv20, 7, 0, 1, 1)
        self.vv18 = QtWidgets.QPushButton(self.lista)
        self.vv18.setObjectName("vv18")
        self.gridLayout.addWidget(self.vv18, 5, 0, 1, 1)
        self.vv21 = QtWidgets.QPushButton(self.lista)
        self.vv21.setObjectName("vv21")
        self.gridLayout.addWidget(self.vv21, 8, 0, 1, 1)
        self.vv10 = QtWidgets.QPushButton(self.lista)
        self.vv10.setObjectName("vv10")
        self.gridLayout.addWidget(self.vv10, 16, 0, 1, 1)
        self.vv31 = QtWidgets.QPushButton(self.lista)
        self.vv31.setObjectName("vv31")
        self.gridLayout.addWidget(self.vv31, 30, 0, 1, 1)
        self.vv26 = QtWidgets.QPushButton(self.lista)
        self.vv26.setObjectName("vv26")
        self.gridLayout.addWidget(self.vv26, 25, 0, 1, 1)
        self.vv11 = QtWidgets.QPushButton(self.lista)
        self.vv11.setObjectName("vv11")
        self.gridLayout.addWidget(self.vv11, 17, 0, 1, 1)
        self.vv12 = QtWidgets.QPushButton(self.lista)
        self.vv12.setObjectName("vv12")
        self.gridLayout.addWidget(self.vv12, 18, 0, 1, 1)
        self.vv13 = QtWidgets.QPushButton(self.lista)
        self.vv13.setObjectName("vv13")
        self.gridLayout.addWidget(self.vv13, 19, 0, 1, 1)
        self.vv6 = QtWidgets.QPushButton(self.lista)
        self.vv6.setObjectName("vv6")
        self.gridLayout.addWidget(self.vv6, 12, 0, 1, 1)
        self.vv4 = QtWidgets.QPushButton(self.lista)
        self.vv4.setObjectName("vv4")
        self.gridLayout.addWidget(self.vv4, 10, 0, 1, 1)
        self.vv5 = QtWidgets.QPushButton(self.lista)
        self.vv5.setObjectName("vv5")
        self.gridLayout.addWidget(self.vv5, 11, 0, 1, 1)
        self.locale1 = QtWidgets.QPushButton(self.lista)
        font = QtGui.QFont()
        font.setUnderline(True)
        self.locale1.setFont(font)
        self.locale1.setStyleSheet("background-color: rgb(221, 237, 255);")
        self.locale1.setObjectName("locale1")
        self.gridLayout.addWidget(self.locale1, 0, 0, 1, 1)
        self.vv9 = QtWidgets.QPushButton(self.lista)
        self.vv9.setObjectName("vv9")
        self.gridLayout.addWidget(self.vv9, 15, 0, 1, 1)
        self.scrollArea.setWidget(self.lista)
        self.gridLayout_2.addWidget(self.scrollArea, 0, 1, 2, 1)
        Cantina.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Cantina)
        self.statusbar.setStyleSheet("")
        self.statusbar.setSizeGripEnabled(True)
        self.statusbar.setObjectName("statusbar")
        Cantina.setStatusBar(self.statusbar)

        self.retranslateUi(Cantina)
        QtCore.QMetaObject.connectSlotsByName(Cantina)

    def retranslateUi(self, Cantina):
        _translate = QtCore.QCoreApplication.translate
        Cantina.setWindowTitle(_translate("Cantina", "MAPPA VASI VINARI"))
        self.mappacantina.setText(_translate("Cantina", "<html><head/><body><p><img src=\"3_Planimetria_Botti.png\"/></p></body></html>"))
        self.vv16.setText(_translate("Cantina", "v.v. 16"))
        self.locale2.setText(_translate("Cantina", "LOCALE 2"))
        self.vv14.setText(_translate("Cantina", "v.v. 14"))
        self.vv22.setText(_translate("Cantina", "v.v. 22"))
        self.vv33.setText(_translate("Cantina", "v.v. 33"))
        self.vv7.setText(_translate("Cantina", "v.v. 7"))
        self.vv32.setText(_translate("Cantina", "v.v. 32"))
        self.vv19.setText(_translate("Cantina", "v.v. 19"))
        self.vv15.setText(_translate("Cantina", "v.v. 15"))
        self.vv27.setText(_translate("Cantina", "v.v. 27"))
        self.vv25.setText(_translate("Cantina", "v.v. 25"))
        self.vv23.setText(_translate("Cantina", "v.v. 23"))
        self.vv8.setText(_translate("Cantina", "v.v. 8"))
        self.vv29.setText(_translate("Cantina", "v.v. 29"))
        self.vv30.setText(_translate("Cantina", "v.v. 30"))
        self.vv17.setText(_translate("Cantina", "v.v. 17"))
        self.locale3.setText(_translate("Cantina", "LOCALE 3"))
        self.vv28.setText(_translate("Cantina", "v.v. 28"))
        self.vv24.setText(_translate("Cantina", "v.v. 24"))
        self.vv20.setText(_translate("Cantina", "v.v. 20"))
        self.vv18.setText(_translate("Cantina", "v.v. 18"))
        self.vv21.setText(_translate("Cantina", "v.v. 21"))
        self.vv10.setText(_translate("Cantina", "v.v. 10"))
        self.vv31.setText(_translate("Cantina", "v.v. 31"))
        self.vv26.setText(_translate("Cantina", "v.v. 26"))
        self.vv11.setText(_translate("Cantina", "v.v. 11"))
        self.vv12.setText(_translate("Cantina", "v.v. 12"))
        self.vv13.setText(_translate("Cantina", "v.v. 13"))
        self.vv6.setText(_translate("Cantina", "v.v. 6"))
        self.vv4.setText(_translate("Cantina", "v.v. 4"))
        self.vv5.setText(_translate("Cantina", "v.v. 5"))
        self.locale1.setText(_translate("Cantina", "LOCALE 1"))
        self.vv9.setText(_translate("Cantina", "v.v. 9"))

#fine prototipo refresh

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.showMaximized()
    sys.exit(app.exec_())